### DISCUSSION TITLE
Hide side bar for non-admin only (conditional)

### DISCUSSION THREAD

**Discussion by Mariusthvdb** [NemesisRE/kiosk-mode#100] [Q&A]
Please let me bring an issue forward, I can not figure out with my current tools.
I need to hide the side bar for non-admin. This is rather straightforward using the non-admin settings:

```
non_admin_settings:
  hide_menubutton: true
```

but, this is too permanent, in my case, I need to allow them every now and give them to access their settings page, to adjust/set a specific setting in the companion app settings....

so, I figured Id create a boolean:

```
template:

  - binary_sensor:
 
      - unique_id: hide_sidebar_for_non_admin
        state: >
          {{is_state('input_boolean.hide_sidebar_for_non_admin','on') and xxx }}
```

to which I can add some other conditions (xxx) or the binary to be 'on'. (ofc, I could also use the boolean for the single setting toggle)

With this, I can toggle my admin boolean, allow them temporary access, and after that toggle back to 'off'

But, I can only use those I the entity_settings, and not the other main settings in Kiosk-mode...

Am I not seeing the obvious, or do I have a challenge here, I hope you can fix somehow..

Guess what I am looking for is smiting like:

```
non_admin_settings:
    entity: binary_sensor.hide_sidebar_for_non_admin
```
or:
```
non_admin_settings:
  - entity:
      binary_sensor.hide_sidebar_for_non_admin: 'on'

```

or maybe even:
```
non_admin_settings:
  hide_sidebar: >
    {{states('binary_sensor.hide_sidebar_for_non_admin')}}
```

This would allow for my generic settings:
admins get the full option of show_side_panel, non_admin users have the sidebar hidden by default, except for specific cases.

Please have a look?
thx!

**Comment by elchininet** [comment]
Hi @Mariusthvdb,

It is not exactly what you are describing, but you can achieve what you are searching knowing the overriding order. Knowing that `entity_settings` rules over the rest of the conditional configs, you could do something like this:

```yaml
non_admin_settings:
  hide_sidebar: true
entity_settings:
  - entity:
       input_boolean.show_sidebar: 'on'
    hide_sidebar: false
```

When `show_sidebar` is `on` it will override the `hide_sidebar` setting under `non_admin_settings`.

**Reply by Mariusthvdb** [reply]
Ha that is actually quite clever ;-) 
Or...

Have to check if that does not interfere with my other settings, specifically the hide_sidebar: false boolean for my admin settings...

Thx for the suggestion !

**Reply by Mariusthvdb** [reply]
there s bit of an unexpected behavior:
I can not toggle any of the settings from another browser window....

using:

```
non_admin_settings:
  hide_sidebar: true
  hide_menubutton: true
  hide_overflow: true
#   ignore_entity_settings: true
```
 
all of the other settings are set by means of the entity boolean setting. No matter what I toggle there, it only changes the browser I am using the toggles in, and not another browser window (with a non_admin user logged in)

moreover, if I use the new:
```
entity_settings:

   - entity:
       binary_sensor.unhide_sidebar_for_non_admin: 'on'
     hide_sidebar: false
```
next to my existing:

```
  - entity:
      input_boolean.hide_sidebar: 'on'
    hide_sidebar: true
```

the complete kiosk made is fluked, and nothing works anymore at all! It breaks Kiosk mode.

so No, that is not the answer for now, we cant have 2 toggles set the same setting.... I might have to fiddle about with a binary_sensor, based on either of these toggles, or use the rephrased toggle (which I dont particularly like, because I want to have them have the same name as the setting they control)

Confess I never tested this before, so it might have been happening forever. Only found out now testing for this functionality for non-admins.

In all honesty, I don't feel it is the best way to have this done (if at all). Seems to me we should be able to have separate settings possible for the main groups, and not rely on overrides.

especially since I have everything showing in admin mode, so the sidebar is already showing (`hide_sidebar: false`), and that new option breaks that functionality.

**Comment by elchininet** [comment]
>all of the other settings are set by means of the entity boolean setting. No matter what I toggle there, it only changes the browser I am using the toggles in, and not another browser window (with a non_admin user logged in)

Let me explain how the entities settings work:

```yaml
- entity:
      input_boolean.hide_sidebar: 'on'
    hide_sidebar: true
```

The above means that when the input boolean is `on`, it sets the `hide_sidebar` in `true`, just that. It doesn‘t mean that if the input boolean is `off` it will set the `hide_sidebar` in `false`. So entities settings will override other conditional configs only when the value of the entity concides with the value that you added to the configuration.

I have a wall tablet with a non-admin user, the sidebar is hidden there, if from my computer I enabled an input boolean with this setting:

```yaml
non_admin_settings:
  hide_sidebar: true
entity_settings:
  - entity:
       input_boolean.show_sidebar: 'on'
    hide_sidebar: false
```

The sidebar is shown in the tablet.

>the complete kiosk made is fluked, and nothing works anymore at all! It breaks Kiosk mode.

I didn‘t have that into account, yes, that would be creating the same setting twice and that would bring issues.

>In all honesty, I don't feel it is the best way to have this done (if at all). Seems to me we should be able to have separate settings possible for the main groups, and not rely on overrides.

It is the way that the options of the library have been implemented, and it was implemented in that way since the beginning it seems. It is a core functionality, it is not something that could be easily changed, having another way of managing the settings is alsmost creating another library with different options.

>especially since I have everything showing in admin mode, so the sidebar is already showing (hide_sidebar: false), and that new option breaks that functionality.

Yes, you mainly want to create different configurations for different users instead of having a central configuration that is how the library was created. The only option is to have settings in the admin machine to show things, not to hide them, these options will not do anything in the admin machine (because everything is shown there), they will only override those accounts or type of users that have settings in place to hide things.

**Reply by Mariusthvdb** [reply]
still I dont get it. sorry.
I hve a toggle in place for all options, but lets focus on this one only.

using my regular entities toggle:
```
  - entity:
      input_boolean.hide_sidebar: 'on'
    hide_sidebar: true
```

I can do as  I like, on all machines, but most importantly my own ;-) (this what I made this for tbh, I didnt think of other users). I want to be able to toggle those, for various reasons at various occasions. Mainly though, I show the sidebar on my admin machine. `input_boolean.hide_sidebar: 'off' ` is default. Or in Kioskmode options: `hide_sidebar: false` is set.

Next, I have the non-admin users, I want to do the opposite. Mainly, Not show, but, on occasion, unhide the sidebar. If I now add that new toggle as you propose, it seems to conflict with my boolean above, as it also sees to hide_sidebar: . Whether that is off or on doesnt seem to matter, the fact I now have 2 booleans for the same config option breaks functionality.

My search therefor remains:
Have a toggle on the admin users to control hide sidebar at all times via that toggle, and `hide_sidebar: false` is default
Have a default `hide_sidebar: true` for non-admin users, but additionally have a toggle to unhide the sidebar for those non-admins.

Put differently: 
we can not toggle settings individually for admin and non-admin users with the current toolset? (not even with some crafty figured out binary_sensor as entity)

....

Just for full reference: I have no admin settings whatsoever.. all I ever did was control the options via the entities settings.

**Comment by Mariusthvdb** [comment]
separate post for clarity.
I seem to have accomplished what I want, and I am not sure why, because I believe to have done this before. nevertheless please check if this is expected:

```
admin_settings:
#  ignore_mobile_settings: true
  hide_sidebar: false

non_admin_settings:
  hide_sidebar: true
  hide_menubutton: true
  hide_overflow: true
  hide_assistant: true
  hide_search: true
#   ignore_entity_settings: true

entity_settings:

  - entity:
      binary_sensor.unhide_sidebar_for_non_admin: 'on'
    hide_sidebar: false

# Hides only the sidebar. Disables swipe to open.
  - entity:
      input_boolean.hide_sidebar: 'on'
    hide_sidebar: true
```

with the above, I can control the sidebar on both by toggling the `input_boolean.hide_sidebar`, and the sidebar  on the non-admin machine by toggling the entity setting the binary_sensor. (this could also have been an input_boolean toggle,  but I had it made already so using it)

Maybe it is  the order of things (controls) here and its the last toggle that is actually acted upon? Not sure tbh, but for now, I can have the defaults for both (and they are opposed), and control them via the interface.

I did already restart and refresh so hopefully it is not cache helping me out here ;-)

I just tested it without the admin settings completely and it still works....
