### DISCUSSION TITLE
Combine differents stats of entity settings

### DISCUSSION THREAD

**Discussion by joaopedros2** [NemesisRE/kiosk-mode#172] [Q&A]
How can I merge these two configs?

I have different 'entity_settings' for 'admin_settings' and 'non_admin_settings'.

```
kiosk_mode:
  non_admin_settings:
    hide_header: true
    hide_sidebar: true
    ignore_entity_settings: false
  entity_settings:
    - entity:
        input_boolean.kiosk_mode: 'on'
      hide_header: true
      hide_sidebar: true
    - entity:
        input_boolean.kiosk_mode: 'off'
      hide_header: false
      hide_sidebar: false


kiosk_mode:
  admin_settings:
    hide_header: true
    hide_sidebar: false
    ignore_entity_settings: false
  entity_settings:
    - entity:
        input_boolean.kiosk_mode: 'on'
      hide_header: true
      hide_sidebar: false
    - entity:
        input_boolean.kiosk_mode: 'off'
      hide_header: false
      hide_sidebar: false
```

Simplified idea:

```
input_boolean.kiosk_mode: 'on'
	admin
		hide = header 
	non_admin
		hide = header, sidebar

input_boolean.kiosk_mode: 'off'
	admin
		hide = nothing 
	non_admin
		hide = nothing
```

**Comment by elchininet** [comment]
Hi @joaopedros2,

`entity_settings` is one of the [Conditional Configurations](https://github.com/NemesisRE/kiosk-mode?tab=readme-ov-file#conditional-lovelace-config), and all Conditional Configurations are placed in the root, they cannot be placed inside any of the others.

As `entity_settings` overrides any other Conditional Configuration, what you are searching could be simpler if you use the boolean entity to show things, not to hide them:

```yaml
kiosk_mode:
  admin_settings:
    hide_header: true
  non_admin_settings:
    hide_header: true
    hide_sidebar: true
  entity_settings:
    input_boolean.disable_kiosk_mode: 'on'
  hide_header: false
  hide_sidebar: false
```

Related discussion: https://github.com/NemesisRE/kiosk-mode/discussions/100

**Comment by joaopedros2** [comment]
I ended up using it like this:

```
kiosk_mode:
  admin_settings:
    hide_header: true
    hide_sidebar: false
    ignore_entity_settings: false
  non_admin_settings:
    hide_header: true
    hide_sidebar: true
    ignore_entity_settings: false
  entity_settings:
    - entity:
        input_boolean.kiosk_mode: 'on'
      hide_header: true
      hide_sidebar: false
    - entity:
        input_boolean.kiosk_mode: 'off'
      hide_header: false
      hide_sidebar: false
```
