### DISCUSSION TITLE
Dynamically change for admin_settings: and non_admin_settings:

### DISCUSSION THREAD

**Discussion by Pro-Control** [NemesisRE/kiosk-mode#185] [Ideas]
for many reasons, I need to change  kiosk mode for admin and non_admin but I can't find a way to do it at the same time only one work  my suggestion if it is possible to do it like below or another way that can control Each category separately :

Example ..:

```
  non_admin_settings:
    - entity:
       input_boolean.kiosk_mode_user: 'on'
       kiosk: true

  admin_settings:
    hide_header: true
    - entity:
       input_boolean.kiosk_mode_admin: 'on'
      kiosk: true
```

**Comment by elchininet** [comment]
Hi @Pro-Control,
Please, check [this discussion](https://github.com/NemesisRE/kiosk-mode/discussions/172). Your configuration is wrong because only [entity_settings](https://github.com/NemesisRE/kiosk-mode?tab=readme-ov-file#entity_settings) admits entities inside and you cannot mix different conditions configs.

**Comment by Pro-Control** [comment]
Hi @elchininet 
thank you for your reply
I know my configuration is wrong I said this suggestion did not match the document ...
All I need is to control Each category separately

**Reply by elchininet** [reply]
Please, check the dicussion that I linked and the related discussion linked to that. Your suggestion did not match the document because it is not supported by the plugin, you would need to change the approach that you are using.

**Reply by Pro-Control** [reply]
@elchininet  I checked it  as  I told you there is no way  to set two input_boolean  to control admin_settings: and non_admin_settings: separately for that I hope to add this feature in future releases

**Reply by elchininet** [reply]
@Pro-Control,
As I mentioned, what you are requesting is not supported, and as it would require to change the way in which all conditional configurations work and the overriding order among them, it is something that could not be achieved without rewriting completely a big part of the library. That is something that will not be done in the near future.
You should change your approach and try to solve your specific use case by other means.
Regards

**Reply by Pro-Control** [reply]
thanks @elchininet, unfortunately, there is no way to  solve it under currently configurations

**Reply by NemesisRE** [reply]
Do I don't understand what you want to do or is the solution just to do this:
```yaml
kiosk_mode:
  admin_settings:
    hide_header: true
  entity_settings:
    - entity:
       input_boolean.kiosk_mode_user: 'on'
      kiosk: true
    - entity:
       input_boolean.kiosk_mode_admin: 'on'
      kiosk: true
```

or even simpler
```yaml
kiosk_mode:
  admin_settings:
    hide_header: true
  entity_settings:
    - entity:
       input_boolean.kiosk_mode: 'on'
      kiosk: true
```

**Reply by elchininet** [reply]
@NemesisRE,
What he is trying to do is to add `entity_settings` under `admin_settings` and under `non_admin_settings` so it can change entities and control admins and non admins separately. Something that is not supported because entity event changes are global (it should be under `kiosk_mode`) and they override any other conditional configuration.

**Reply by NemesisRE** [reply]
So it's the first code?
oh no I see if any entity setting switches kiosk on it's on

That means the simpliest solution could be to have one input_boolean for global kiosk mode and maybe a link in the admin dashboard with the url parameter

**Reply by elchininet** [reply]
>So it's the first code?

Not really, because when one changes something with entities (for example `kiosk: true`) it changes overall (for admins and non admins, at least that there is an `ingnore_entity_settings` under those). So having two inputs that sets the same global variable will not make that it only works for admins or non admins.

>oh no I see if any entity setting switches kiosk on it's on

That's right.

That would require not only to create entity change events for users, admins, non admins and mobiles, but also to rethink and change the whole overriding logic of all conditional configs.

With `kiosk-mode` one normally wants to apply things for certain users, or specific things for admins and non-admins but it is a very specific case to do it dynamically for both separately, something that is not supported.

**Comment by elchininet** [comment]
Hi @Pro-Control,

[This pull request](https://github.com/NemesisRE/kiosk-mode/pull/274) contains something in which I have been working lately and it is related in some way to this discussion. Please, read the description of the pull request but you can also check [the documentation in the branch](https://github.com/NemesisRE/kiosk-mode/tree/support_for_jinja_templates).

Please, if you can test [this gist](https://gist.github.com/elchininet/9a2648ea0016d3194072712c745c5ad2) and check if you can spot errors or unwanted issues it would be helpful.

Regards

**Comment by sirmeili** [comment]
I know this is a bit old, but +1.

For my use case, I have mobile and then I have desktop. When I'm on the desktop, I don't want the toggle to affect the menu/header. I want them there all the time, but when I'm on mobile I want my entity to control if the menu shows or not.

**Reply by elchininet** [reply]
Hi @sirmeili,
Refer to [the above comment](https://github.com/NemesisRE/kiosk-mode/discussions/185#discussioncomment-10649034).
Regards

**Reply by sirmeili** [reply]
@elchininet I guess the first time I read that, it didn't seem like it would work for my use case, but perhaps it will. Any clue as when this will be brought into a release?

**Reply by elchininet** [reply]
>it didn't seem like it would work for my use case

It will work for your use case because you can make a template including the device's user-agent and the state of an entity. Something like this:

```yaml
hide_header: |
   [[[
      return (
        user_agent.includes('Android') &&
        is_state("input_boolean.hide_header", "on")
      );
   ]]]'
```

The previous code will hide the header if the `input_boolean.hide_header` is `on` but only in a device which user agent contains `Android`.

>Any clue as when this will be brought into a release?

Unfortunately, no much interest from the community to test it. I created a gist just to make it possible to test it because it is a radical change and I would like to know if it brings any issue in real cases scenarios before releasing it. If you can test it on your set up and report back after some time testing it it would be helpful. I'll update the gist with the latest code in master.

**Reply by elchininet** [reply]
Gist updated

**Reply by sirmeili** [reply]
How can I help test it?

**Reply by sirmeili** [reply]
So I figured out how to update it.  not  a big deal, but here is what I had before:

```
kiosk_mode:

  non_admin_settings:
    hide_header: true
    ignore_entity_settings: true
  mobile_settings:
    hide_header: true
    ignore_entity_settings: false
  entity_settings:
    - entity:
        input_boolean.kiosk_mode: 'on'
      hide_header: true
    - entity:
        input_boolean.kiosk_mode: 'off'
      hide_header: false.
```

This does not give me 100% of what I want, which is:

all non-admin users, always hide the header, and ignore entity settings
on mobile, hide the header, but allow entity settings ONLY if I'm an admin (I assume the former overrides this one in the normal code?)
if I'm not on mobile, show the header.

I noticed in your branch, ignore_entity_settings has been removed as an option (at least from the documentation).
