### DISCUSSION TITLE
Secure dash when device is locked (Android Device Controls Panel)

### DISCUSSION THREAD

**Discussion by patienttruth** [NemesisRE/kiosk-mode#242] [Q&A] [answered]
Greetings,

Is there any difference as to how kiosk mode is applied to a view linked from a dash?

I have a "phone" dash that links to some "shared" views. The home assistant companion app gives this to Android for the Device Controls Panel.

The simple `kiosk:true` works for the phone dash, but I'm seeing my header bar and menus on the views. I've put the following into my raw config on the shared dash that contains the views, but the header and menu with "edit" still show up. I believe there are a few redundant entries, this was my attempts to get this to work.

```yaml
kiosk_mode:
  entity_settings:
    - entity:
        binary_sensor.arbutus_device_locked: 'on'
        hide_dialog_header_action_items: true
        hide_overflow: true
        kiosk: true
        block_overflow: true
        hide_edit_dashboard: true
  hide_search: true
  hide_assistant: true
```

My goal is to "batten down the hatch" for settings and backend access when the dash is accessed from the Android "device controls" panel while the phone is locked.

Thanks!

**Comment by patienttruth** [comment]
Of note, it seems `entity_settings` is what's not working. As both the `hide_search` and `hide_assistant` are working on the view.

I have the entity status displayed on the dash for debugging and it shows "on" when the device is locked.

**Reply by elchininet** [reply, marked as answer]
Hi @patienttruth,

Check [entity_settings entry in the documentation](https://github.com/NemesisRE/kiosk-mode?tab=readme-ov-file#entity_settings). In `yaml`, indentation is crucial:

```yaml
kiosk_mode:
  entity_settings:
    - entity:
        input_boolean.hide_sidebar: 'on'
      hide_sidebar: true
    - entity:
        sensor.hide_header: 'on'
      hide_header: true
    - entity:
        input_text.kiosk: 'true'
      kiosk: true

```

For your understanding, I will translate your `yaml` code to `json` so you can spot where the issue is. You have this config:

```json
{
  "kiosk_mode": {
    "entity_settings": [
      {
        "entity": {
          "binary_sensor.arbutus_device_locked": "on",
          "hide_dialog_header_action_items": true,
          "hide_overflow": true,
          "kiosk": true,
          "block_overflow": true,
          "hide_edit_dashboard": true
        }
      }
    ]
  }
}
```

But it should be:

```json
{
  "kiosk_mode": {
    "entity_settings": [
      {
        "entity": {
          "binary_sensor.arbutus_device_locked": "on"
        },
        "hide_dialog_header_action_items": true,
        "hide_overflow": true,
        "kiosk": true,
        "block_overflow": true,
        "hide_edit_dashboard": true
      }
    ]
  }
}
```

Regards
