### DISCUSSION TITLE
kiosk mode - header card

### DISCUSSION THREAD

**Discussion by AndreL79** [NemesisRE/kiosk-mode#306] [Ideas]
is it possible different settings header_card for different user?

```
kiosk_mode:
  user_settings:  
    - users:
        - kiosk
      hide_header_card: true
```
