### ISSUE TITLE
[BUG]  some options don't work on chrome-browser Raspberry

### ISSUE THREAD

**Issue by duedipicche** [NemesisRE/kiosk-mode#102]
I installed home assistant on a raspberry p3b+ and use chrome-browser to view on a 10.1" hdmi display.

- Home Assistant ver. 2023.7.1
- Kiosk Mode ver. 3.0.0 (but i try also 2.0)
- Raspberry Pi 3 B+ with bullseyes
- 
my yaml file:
```
kiosk_mode:
  non_admin_settings:
    hide_search: true
    hide_assistant: true
    hide_overflow: true
views:
  - title: Raspberry 
```

- hide_header: **work**
- hide_sidebar: **work**
- hide_search: **not work**
- hide_assistant: **not work**
- hide_overflow: **not work**

I tried both with **non_admin_mode** and without.
If i install firefox-esr on Raspberry everything works.

![IMG20230715135451](https://github.com/NemesisRE/kiosk-mode/assets/38075965/dd36e421-4bd1-46ea-ba51-01225111b1fb)

![IMG20230715135015](https://github.com/NemesisRE/kiosk-mode/assets/38075965/9c12824e-7047-402a-a444-5aaa45b490d3)

Thank you for any attention and sorry for my bad English.
