### ISSUE TITLE
Kiosk mode not activting

### ISSUE THREAD

**Issue by mirkin-pixel** [NemesisRE/kiosk-mode#11]
I installed kiosk-mode via HACS and added this to the dashboard:
```
title: ''
kiosk_mode:
  hide_header: true
  ignore_mobile_settings: true
views:
[...]
```

The header keeps showing on the top.
