### ISSUE TITLE
hide Assistant does not hide the icon

### ISSUE THREAD

**Issue by Mariusthvdb** [NemesisRE/kiosk-mode#16]
thx for adding the hide search and hide assistant options.

I can hide the search icon using
```
# Hides the search icon
  - entity:
      input_boolean.hide_search: 'on'
    hide_search: true
```

and the same for the account, which is kind of neat indeed

However, using
```
# Hides the assistant icon
  - entity:
      input_boolean.hide_assistant: 'on'
    hide_assistant: true
```

does Not hide the assistant icon unfortunately.

Ive added all booleans in a card, to easily control settings:

<img width="478" alt="Scherm­afbeelding 2023-03-14 om 23 09 20" src="https://user-images.githubusercontent.com/33354141/225153597-c156df63-f390-4d8c-b7d0-1ce6e64a64d3.png">

**Comment by elchininet** [comment]
Hi @Mariusthvdb,

The `hide_assistant` option what does is to hide the second `ha-icon-button` inside `app-toolbar`, this is not perfect because if Home Assistant front-end code changes this needs to be changed too but it is better than the previous behaviour (all the buttons getting hide if the `hide_search` is `true`).

Please, could you share what is the HTML structure of your header? Just to see which is the second `ha-icon-button` for you. On my side this is what I get using the `hide_assistant` option:

![image](https://user-images.githubusercontent.com/3728220/225592735-c2a9ca5b-21e8-48fb-a920-65a807aa9f06.png)

**Comment by Mariusthvdb** [comment]
seeing this in Chrome. What browser are you using?

<img width="928" alt="Scherm­afbeelding 2023-03-16 om 12 20 32" src="https://user-images.githubusercontent.com/33354141/225601805-99f554e6-3beb-44a4-a5f9-460fc06fdd65.png">

**Comment by elchininet** [comment]
For the screenshot I used Firefox, but regularly I test the code with Opera, Safari, Firefox and Chrome. This is the same result in Chrome:

![image](https://user-images.githubusercontent.com/3728220/225603677-41c3cbe1-831f-4f92-b6c7-4db6a47bbac1.png)

At least we know that your second button is indeed the Assistant one. So, let‘s debug this further. Could you try to apply the option without the entity config?, I mean, directly in the configuration to see if it doesn‘t occur there. Trying to isolate the issue. Also, try to clean the local storage to see if this is not related to some cache issue.

**Comment by Mariusthvdb** [comment]
Ive set it fixed in the kiosk_mode config for now and yes, that makes a difference....


<img width="220" alt="Scherm­afbeelding 2023-03-16 om 12 39 43" src="https://user-images.githubusercontent.com/33354141/225605927-43c5cd70-5327-4ac5-9962-a5b49ed77dba.png">

now can that be? did I make a mistake in the boolean config? let me double check:

this is my full config:
```
hide_assistant: true

non_admin_settings:
  hide_menubutton: true
  hide_overflow: true
  ignore_entity_settings: true

mobile_settings:
  hide_menubutton: true
  hide_overflow: true
#   ignore_entity_settings: true

entity_settings:
#Hides both the header and sidebar.
  - entity:
      binary_sensor.kiosk_mode: 'on'
#      input_select.mode: Kiosk
    kiosk: true
# Hides only the header
  - entity:
      input_boolean.hide_header: 'on'
    hide_header: true
# Hides only the sidebar. Disables swipe to open.
  - entity:
      input_boolean.hide_sidebar: 'on'
    hide_sidebar: true
# Hides only the sidebar menu icon. Does not disable swipe to open.
  - entity:
      input_boolean.hide_menubutton: 'on'
    hide_menubutton: true
# Hides the top right menu
  - entity:
      input_boolean.hide_overflow: 'on'
    hide_overflow: true
# Hides the account icon
  - entity:
      input_boolean.hide_account: 'on'
    hide_account: true
# Hides the search icon
  - entity:
      input_boolean.hide_search: 'on'
    hide_search: true
# # Hides the assistant icon
#   - entity:
#       input_boolean.hide_assistant: 'on'
#     hide_assistant: true
```

and this is the boolean:

<img width="582" alt="Scherm­afbeelding 2023-03-16 om 12 41 18" src="https://user-images.githubusercontent.com/33354141/225606329-78a05e18-c6d8-4692-b873-09d026abf299.png">
