### ISSUE TITLE
[BUG] Assist Button Appears when Hide_Assistant: True

### ISSUE THREAD

**Issue by BillyFKidney** [NemesisRE/kiosk-mode#170]
**Describe the bug**
I have kiosk mode and hide assistant set to true but it still appears in my dashboard. 🫣

**To Reproduce**
Raw code from dashboard.

```
kiosk_mode:
  user_settings:
    - users:
        - Kitchen Tablet
        - Master Bedroom Tablet
        - Hallway Tablet
      hide_sidebar: true
      hide_search: true
      hide_assistant: true
      hide_overflow: true
views:
  - title: Home
    type: panel
    badges: []
    cards:
      - type: horizontal-stack
```

**Expected behavior**
Nothing to show on the top row. 😜

**Screenshots**
![IMG_0869](https://github.com/NemesisRE/kiosk-mode/assets/65253277/2eda1c57-4341-4898-9bfc-3889ec98d0f5)
![IMG_0870](https://github.com/NemesisRE/kiosk-mode/assets/65253277/840ecf34-d02d-468b-a466-dcd9feeae397)

**Versions:**
 - Home Assistant: 2023.12.4
 - Supervisor: 2023.12.0
 - Operating System: 11.2
 - Frontend: 20231208.2
 - Kiosk-Mode: 5.1.0

**Additional context**
Picture of tablet is the “Kitchen Tablet” user running Fully-Kiosk on a Samsung A8 tablet
