### ISSUE TITLE
iOS app issues

### ISSUE THREAD

**Issue by DanDon** [NemesisRE/kiosk-mode#2]
There is an issue where kiosk mode works when initially loading the dashboard on iOS (iPad) app but after the device goes to sleep and then wakes from sleep, the header bar appears. The side bar stays hidden but the header shows and can only be hidden again by reloading that dashboard. Either by going to another dashboard and back again or closing the app and re-opening.

**Comment by NemesisRE** [comment]
I have no "I" devices so I would need help to patch that

**Comment by elchininet** [comment]
Hi @DanDon,
Could you confirm if this still happens for you?
Regards

**Comment by gwww** [comment]
I believe I might have the same issue. It just started when I updated to 1.8.x. I also updated to latest HA 2023.4.

What happens is that `hide_header` no longer works on the iOS app. It was working before I updated - I'm guessing I was on 1.7.8 prior to the bug happening. 

I have tried closing the iOS app and restarting. Refreshing the screen. Turning hide on/off (see my config below) did not make a difference. No matter what the header was also shown. I'm an running the latest HA iOS app from a couple of days ago. But, I did also test on the previous version of the iOS app and hide did not work.

I also tried using Safari on my phone to sign into my HA instance and `hide_header` works properly there.

So, something new in either the latest kiosk mode or in the latest HA 2023.4 release would appear to be the problem and how one of those is interacting with the iOS app.

```
kiosk_mode:
  entity_settings:
    - entity:
        input_boolean.kiosk_mode: 'on'
      hide_header: true
    - entity:
        input_boolean.kiosk_mode: 'off'
      hide_header: false
```
