### ISSUE TITLE
[BUG] settings need reload to actually happen

### ISSUE THREAD

**Issue by Mariusthvdb** [NemesisRE/kiosk-mode#271]
**Describe the bug**

before, when toggling the booleans that I  have configured to control the Kiosk mode options, the toggle would immediately change the frontend.

As of late, I need to reload the view for the change to appear.

Also, when not reloading but changing another option, that causes the former toggle to kick in. So it seems as if the wrong boolean was toggled

 - Console log errors (F12)
No errors

**To Reproduce**

**Expected behavior**

toggle immediately changing frontend. As it has always done

**Screenshots**
<img width="517" alt="Scherm­afbeelding 2024-09-13 om 22 46 23" src="https://github.com/user-attachments/assets/252741e3-6537-47ad-92e0-d864c0ec56c0">

**Versions:**
 - Home Assistant: 2024.9.1

 - Kiosk-Mode 6.1.1

**Additional context**

my kiosk mode settings (which I havent changed since march 2023).... :

```
# https://github.com/maykar/kiosk-mode#config-options
# https://github.com/NemesisRE/kiosk-mode
# admin_settings:
# #  ignore_mobile_settings: true
#   hide_sidebar: false

# hide_assistant: true

non_admin_settings:
  hide_sidebar: true
  hide_menubutton: true
  hide_overflow: true
  hide_assistant: true
  hide_search: true
#   ignore_entity_settings: true

mobile_settings:
  hide_menubutton: true
  hide_overflow: true
#   ignore_entity_settings: true

entity_settings:

  - entity:
      binary_sensor.unhide_sidebar_for_non_admin: 'on'
    hide_sidebar: false

#Hides both the header and sidebar.
  - entity:
      binary_sensor.kiosk_mode_selected: 'on'
#      input_select.mode: Kiosk
    kiosk: true
# Hides only the header
  - entity:
      input_boolean.hide_header: 'on'
    hide_header: true
# Hides only the sidebar. Disables swipe to open.
  - entity:
      input_boolean.hide_sidebar: 'on'
    hide_sidebar: true
# Hides only the sidebar menu icon. Does not disable swipe to open.
  - entity:
      input_boolean.hide_menubutton: 'on'
    hide_menubutton: true
# Hides the top right menu
  - entity:
      input_boolean.hide_overflow: 'on'
    hide_overflow: true
# Hides the account icon
  - entity:
      input_boolean.hide_account: 'on'
    hide_account: true
# Hides notification tray
  - entity:
      input_boolean.hide_notitications: 'on'
    hide_notifications: true
# Hides the search icon
  - entity:
      input_boolean.hide_search: 'on'
    hide_search: true
# Hides the assistant icon
  - entity:
      input_boolean.hide_assistant: 'on'
    hide_assistant: true
# Hides refresh menu item
  - entity:
      input_boolean.hide_refresh: 'on'
    hide_refresh: true
# Hides the unused entities menu item
  - entity:
      input_boolean.hide_unused_entities: 'on'
    hide_unused_entities: true
# Hides the reload resources menu item
  - entity:
      input_boolean.hide_reload_resources: 'on'
    hide_reload_resources: true
# Hides edit dashboard menu item
  - entity:
      input_boolean.hide_edit_dashboard: 'on'
    hide_edit_dashboard: true
# Block mouse on empty overflow menu-items
  - entity:
      binary_sensor.kiosk_mode_block_overflow: 'on'
    block_overflow: true
# Block mouse on overflow menu-items
  - entity:
      input_boolean.kiosk_mode_block_mouse: 'on'
    block_mouse: true

  - entity:
      input_boolean.hide_dialog_header_action_items: 'on'
    hide_dialog_header_action_items: true
  - entity:
      input_boolean.hide_dialog_header_history: 'on'
    hide_dialog_header_history: true
  - entity:
      input_boolean.hide_dialog_header_settings: 'on'
    hide_dialog_header_settings: true
  - entity:
      input_boolean.hide_dialog_header_overflow: 'on'
    hide_dialog_header_overflow: true

  - entity:
      input_boolean.hide_dialog_history: 'on'
    hide_dialog_history: true
  - entity:
      input_boolean.hide_dialog_history_show_more: 'on'
    hide_dialog_history_show_more: true

  - entity:
      input_boolean.hide_dialog_logbook: 'on'
    hide_dialog_logbook: true
  - entity:
      input_boolean.hide_dialog_logbook_show_more: 'on'
    hide_dialog_logbook_show_more: true

  - entity:
      input_boolean.hide_dialog_attributes: 'on'
    hide_dialog_attributes: true

  - entity:
      input_boolean.hide_dialog_media_actions: 'on'
    hide_dialog_media_actions: true
  - entity:
      input_boolean.hide_dialog_update_actions: 'on'
    hide_dialog_update_actions: true
  - entity:
      input_boolean.hide_dialog_climate_actions: 'on'
    hide_dialog_climate_actions: true
  - entity:
      input_boolean.hide_dialog_timer_actions: 'on'
    hide_dialog_timer_actions: true
```

**Comment by elchininet** [comment]
Hi @Mariusthvdb,
You need to check what is happening on your side and what provoked that, but the `entity_settings` are working perfect on my Home Assistant instance without any reload (`2024.9.1`). But just to be double sure I opened the demo that we have set up here in the repo for the end-to-end tests which is now running on `2024.9.1` too. As this is a fresh instance just with the plugin installed is the best one to perform these tests:

![kiosk-mode](https://github.com/user-attachments/assets/18ee603b-4762-473b-b388-34a512426d60)

Take into account that the last release was in Agugust 20th (which contained only dependencies updates to dev packages not related to the plugin code), the real change to the code was in `v6.1.0` on July 22th. When did you notice that behaviour in your instance?

Regards

**Comment by Mariusthvdb** [comment]
ill try to drop a screen vid, so you can see what's happening.

tbh, most of my frontend stuff is automated, so I hardly ever manually toggle them. but I noticed today, because someone else in the [community said Kiosk mode didnt work](https://community.home-assistant.io/t/how-to-hide-unhide-sidebar-and-topbar-with-a-toggle-switch/769997/8?u=mariusthvdb)

**Comment by elchininet** [comment]
Well, the library is not the culprit for what is ocurring to you, I can asure you that. The end-to-end tests that we have in place would break if something like that occurs and they are working even with [the Nightly Beta Tests](https://github.com/NemesisRE/kiosk-mode/actions/workflows/ha-beta-tests.yaml). Let's try to figure it out what is provoking that behaviour on your side. I'll record the screen so you can do the same on your side and learn how to debug that.

https://github.com/user-attachments/assets/3bfe26f7-9fc0-4119-a684-3755abe8d9e0

Verify that the proper style element is being added to that shadow root.

**Comment by elchininet** [comment]
>wild guess: could it have to do with Sections?
>recently I changed from default (masonry) or custom layout views to sections on many views, also this particular view:

Just check your layout to see if it looks like the one in the video, we are going to figure it out, no worries.

**Comment by Mariusthvdb** [comment]
quick feedback:

it's not my theming: ive tested using default theme (homeassistant default) and behavior is identical
it's not the layout: returning to custom layout doesnt change behavior

any toggle is 1 state change behind

need to check your vid, will do next

**Comment by Mariusthvdb** [comment]
well, this is unexpected, Ive found the issue:

I've added a custom resource of myself recently, that can inject templates on attributes, which I need for 1 specific reason.

Disabling that immediately returns the correct functionality to Kiosk-mode.....
Which is great on the 1 hand, since this plugin is not flawed 🎉 

Otoh... 
@elchininet could I ask you to please have a look at the [new feature ](https://github.com/Mariusthvdb/custom-ui/blob/master/README.md#news) and the [resource js file](https://github.com/Mariusthvdb/custom-ui/blob/master/custom-attributes-templates.js) ?

it is a miniature of the former custom-ui that never caused anything like this, so maybe I made an error after all there.

Closing this issue here

**Comment by ausfas** [comment]
I can confirm that 
```
kiosk_mode:
  kiosk: true
```
works but following doesn't
```
kiosk_mode:
  entity_settings:
    - entity: input_select.theme_selector
      state: ios-dark-mod
      hide_sidebar: true
      hide_header: true
```

**Comment by ausfas** [comment]
> well, this is unexpected, Ive found the issue:
> 
> I've added a custom resource of myself recently, that can inject templates on attributes, which I need for 1 specific reason.
> 
> Disabling that immediately returns the correct functionality to Kiosk-mode..... Which is great on the 1 hand, since this plugin is not flawed 🎉
> 
> Otoh... @elchininet could I ask you to please have a look at the [new feature ](https://github.com/Mariusthvdb/custom-ui/blob/master/README.md#news) and the [resource js file](https://github.com/Mariusthvdb/custom-ui/blob/master/custom-attributes-templates.js) ?
> 
> it is a miniature of the former custom-ui that never caused anything like this, so maybe I made an error after all there.
> 
> Closing this issue here

but its not working for me :(

**Comment by elchininet** [comment]
>Disabling that immediately returns the correct functionality to Kiosk-mode.....
>Which is great on the 1 hand, since this plugin is not flawed 🎉

Glad to hear that you found the issue.

>Otoh...
>@elchininet could I ask you to please have a look at the [new feature ](https://github.com/Mariusthvdb/custom-ui/blob/master/README.md#news)and the [resource js file](https://github.com/Mariusthvdb/custom-ui/blob/master/custom-attributes-templates.js) ?
>
>it is a miniature of the former custom-ui that never caused anything like this, so maybe I made an error after all there.

I'll take a look to see if I spot something but `custom-ui` was used by several people, Iam sure that the issue is not coming from there.

**Comment by elchininet** [comment]
> I can confirm that
> 
> ```
> kiosk_mode:
>   kiosk: true
> ```
> 
> works but following doesn't
> 
> ```
> kiosk_mode:
>   entity_settings:
>     - entity: input_select.theme_selector
>       state: ios-dark-mod
>       hide_sidebar: true
>       hide_header: true
> ```

That makes total sense because the first is a good configuration and the second is not correct.

Check the examples in [the documentation](https://github.com/NemesisRE/kiosk-mode?tab=readme-ov-file#entity_settings) for the `entity_settings`. The indentation is not right and it should not have a `state` field.

This should work:

```yaml
kiosk_mode:
  entity_settings:
    - entity:
        input_select.theme_selector: 'ios-dark-mod'
      hide_sidebar: true
      hide_header: true
```

Let me know if it works and if it is not working for you open a new issue just to keep track of each one separately.

Regards

**Comment by ausfas** [comment]
Ok, I can confirm the same findings. Checked in FireFox, Edge and Opera broswers, the input select doesn't work but the input_boolean does. Here is the code:
```
kiosk_mode:
  admin_settings:
    hide_sidebar: false
    hide_header: false
  mobile_settings:
    hide_header: false
    hide_sidebar: true
    ignore_entity_settings: true
    custom_width: 768
  user_settings:
    - users:
        - Test
      hide_sidebar: false
      hide_header: false
  entity_settings:
    - entity:
        input_select.theme_selector: ios-dark-mod
      hide_sidebar: true
      hide_header: true
    - entity:
        input_boolean.hide_sidebar: 'on'
      hide_sidebar: true
      hide_header: true
views:
  - title: Home
    cards:
      - type: entities
        entities:
          - input_select.theme_selector
      - type: entities
        entities:
          - input_boolean.hide_sidebar
  ```
One more point that I've automation for switching themes, is this causing an issue as the input_select change the theme but no effect for kiosk settings. 
```
alias: Switch Theme
description: ""
trigger:
  - platform: state
    entity_id: input_select.theme_selector
action:
  - data_template:
      name: "{{ states('input_select.theme_selector') }}"
    action: frontend.set_theme

```
