### ISSUE TITLE
where to add the config ???

### ISSUE THREAD

**Issue by diginfo** [NemesisRE/kiosk-mode#29]
Where exactly does this go ?

I tried adding it into configuration.yaml:

```
lovelace            : !include pac/yaml/lovelace.yaml
```
```
# include pac/yaml/lovelace.yaml
kiosk_mode:
  user_settings:
    - users:
        - paul
      hide_sidebar: true
    - users:
        - dave
      kiosk: true
      ignore_entity_settings: true
```
That does not work.

```
find . -name "lovelace"
>> ./.storage/lovelace
```
The only files found in .storeage/lovelace* - are json format, I have no clue where to add this code :-)

```
kiosk_mode:
  hide_header: true
  
views:
Note: views: is added in the example above to show where kiosk_mode: should be placed in your Lovelace config
```

Where precisely path/filename is this: ```should be placed in your Lovelace config```
