### ISSUE TITLE
[SETUP HELP] Integration error: kiosk_mode - Integration 'kiosk_mode' not found.

### ISSUE THREAD

**Issue by DAE51D** [NemesisRE/kiosk-mode#309]
I swear this Kiosk Mode did work a while ago when I first installed it, but now since HACS 2.0 or something when I uncommented the code I had (working before) it doesn't now...

`Integration error: kiosk_mode - Integration 'kiosk_mode' not found.`

![image](https://github.com/user-attachments/assets/586fc17a-dd47-4636-ad85-b06dadab65cc)

I've tried with both of these lines in my `/homeassistant/configuration.yaml` (and a few other permutations) to no avail
```yaml
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/kiosk-mode/kiosk-mode.js?v6.4.0
    # - /config/www/community/kiosk-mode/kiosk-mode.js?v6.4.0

kiosk_mode:
  user_settings:
    - users:
        - "airbnb"
      hide_sidebar: true
      kiosk: true
      ignore_entity_settings: true
```

I've even tried re-downloading, and uninstalling and re-installing in case... always this same error as above.

Additionally if I look at the actual file system, I can see the files in `/config/www/community/kiosk-mode` and I do NOT see `/hacsfiles` (or a symlink or anything, should there be??)
![image](https://github.com/user-attachments/assets/18e15dc8-bc47-4609-9415-8e97b6d9320d)
