### ISSUE TITLE
Seems to be broken as of Core 2023.04.0

### ISSUE THREAD

**Issue by bkr1969** [NemesisRE/kiosk-mode#32]
No matter what I do, the header will not hide. Code has not changed:

```
kiosk_mode:
  hide_header: true
views:
  - title: New Down
    path: downstairs
...
```
