### ISSUE TITLE
[FR] Disable vertical scrolling?"

### ISSUE THREAD

**Issue by Jaxel** [NemesisRE/kiosk-mode#328]
Can we get an option to disable scrolling on a dashboard?

**Comment by elchininet** [comment]
Hi @Jaxel,
What would  be the use case of that request? Is it not enough to avoid putting too many elements in that dashboard to avoid the vertical scrolling?
Regards

**Comment by Jaxel** [comment]
It's hard to explain in text what's happening here, so I made some videos:

![PXL_20250101_155124725-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/e847f1a3-7cfe-4f0e-b4db-4cd6fc723557)

And here is a longer video explaining the exact HTML/CSS issue:
https://www.youtube.com/watch?v=xzJ2rAnEv08

**Comment by elchininet** [comment]
>It's hard to explain in text what's happening here, so I made some videos:
>And here is a longer video explaining the exact HTML/CSS issue:
>https://www.youtube.com/watch?v=xzJ2rAnEv08

Thanks @Jaxel, it is clear now.
That falls out of the scope of the plugin. Instead of trying to add an option to resolve your specific use case, let's try to triage from which place is your issue coming. I cannot reproduce it in the Docker demo, so I suspect that it is coming from your theme or something that you have set up. Let's try to rule out things, are you using a theme or you are using the default Home Assistant theme?

**Comment by Jaxel** [comment]
Default theme. Only happens when Kiosk mode is enabled.

**Comment by elchininet** [comment]
>Default theme.

Perfect, let's keep ruling out things, could you tell me which layout you are using?

>Only happens when Kiosk mode is enabled.

It makes sense, because in `kiosk-mode` there is no header 🙂

But as the Docker demo is a Home Assistant instance without anything else installed but `kiosk-mode` it is the perfect place to reproduce things. If it is not happening there by default, then the way to go is to try to reproduce your set up to detect what is causing the issue.

**Comment by Jaxel** [comment]
It also only happens on my Samsung A9+ tablets. Doesn't happen on my cell phone.

**Comment by elchininet** [comment]
>It also only happens on my Samsung A9+ tablets

I have a Galaxy Tab A8 so maybe I can reproduce it there, let me know which layout you are using to build something similar to yours.

**Comment by Jaxel** [comment]
It's a YAML layout.

**Comment by Jaxel** [comment]
I have HACS with card-mod, Spook, and Paper Buttons Row installed. That's it.

**Comment by elchininet** [comment]
>It's a YAML layout.

I don't mean that. In a dashboard, each view can have a layout (Sections, Masonry, etc). Looking at your screen it could be a Masonry one but I am not sure.

**Comment by Jaxel** [comment]
YAML layouts are masonry.

**Comment by elchininet** [comment]
>YAML layouts are masonry.

I think that you don't get what I am asking, this is one of the dashboards in the Docker demo, all the dashboards are writing in YAML:

```yaml
kiosk_mode:
  hide_header: true
title: Kiosk-mode hide header
views:
  - theme: Backend-selected
    title: Hide Header
    path: kiosk-mode-hide-header
    badges: []
    cards:
      - type: markdown
        content: This dashboard has the setting `hide_header` on `true`.
```

But I can set up the layout if I want:

```yaml
type: xxx ## <--- here is set up the layout (e.g. sections)
kiosk_mode:
  hide_header: true
title: Kiosk-mode hide header
views:
  - theme: Backend-selected
    title: Hide Header
    path: kiosk-mode-hide-header
    badges: []
    cards:
      - type: markdown
        content: This dashboard has the setting `hide_header` on `true`.
```

Let me know if you are using any layout.

**Comment by Jaxel** [comment]
```
kiosk_mode:
  kiosk: true

views:
  - title: Overview
    path: overview
    cards:
      - !include overview-column-1.yaml
      - !include overview-column-2.yaml
      - !include overview-column-3.yaml
```
YAML layouts are Masonry by default.

**Comment by elchininet** [comment]
>YAML layouts are Masonry by default.

There are no such thing as "YAML layouts" 🙂

I think that you mean that you use `YAML` mode instead of storage mode, but that doesn't define the layout of a view. Looking at your code you don't have any layout set up, so it is Masonry in that case as in the docker demo. Could you post the code of the view in which you have your cameras? In that way I can set up a similar one in the docker demo.

**Comment by Jaxel** [comment]
```
kiosk_mode:
  kiosk: true

views:
  - title: Cameras
    path: cameras
    theme: cameras
    cards:
      - !include cameras-column-1.yaml
      - !include cameras-column-2.yaml
      - !include cameras-column-3.yaml
```

```
type: vertical-stack
cards:
  - type: heading
  - type: heading
  - type: heading
  - type: heading
  - type: heading
  - type: heading
  - type: heading
  - type: heading
  - type: heading
  - type: heading
    
  - type: picture-entity
    entity: camera.door_bell_porch
    camera_image: camera.door_bell_porch
    camera_view: live
    aspect_ratio: "3:4"
    show_state: false
    show_name: false
    tap_action: none
```

```
type: vertical-stack
cards:
  - type: heading
  - type: heading
  - type: heading
  - type: heading
  - type: heading
  - type: heading
  - type: heading
  - type: heading
  - type: heading
  - type: heading
    
  - type: heading
    icon: mdi:home-outline
    heading: Camera @Driveway
    
  - type: picture-entity
    entity: camera.camera_driveway
    camera_image: camera.camera_driveway
    camera_view: live
    aspect_ratio: "16:9"
    show_state: false
    show_name: false
    tap_action: none
    
  - type: picture-entity
    entity: camera.camera_garage
    camera_image: camera.camera_garage
    camera_view: live
    aspect_ratio: "16:9"
    show_state: false
    show_name: false
    tap_action: none
    
  - type: heading
    icon: mdi:car-outline
    heading: Camera @Garage
```

```type: vertical-stack
cards:
  - type: heading
  - type: heading
  - type: heading
  - type: heading
  - type: heading
  - type: heading
  - type: heading
  - type: heading
  - type: heading
  - type: heading
    
  - type: heading
    icon: mdi:pool
    heading: Camera @Patio
    
  - type: picture-entity
    entity: camera.camera_patio
    camera_image: camera.camera_patio
    camera_view: live
    aspect_ratio: "16:9"
    show_state: false
    show_name: false
    tap_action: none
    
  - type: picture-entity
    entity: camera.camera_living_room
    camera_image: camera.camera_living_room
    camera_view: live
    aspect_ratio: "16:9"
    show_state: false
    show_name: false
    tap_action: none
    
  - type: heading
    icon: mdi:theater
    heading: Camera @Living Room
```
