### ISSUE TITLE
[FR]

### ISSUE THREAD

**Issue by ardstuebck** [NemesisRE/kiosk-mode#333]
Hi,

Thank you for your great work on this project!

I have a feature suggestion that could enhance privacy for some users. It would be helpful to have an option to hide the “Last Modified” information, particularly in the Lock Dialog. In scenarios like mine, this would prevent unauthorized individuals from gaining insight into when devices were last controlled or modified.

![image](https://github.com/user-attachments/assets/6cd54e42-252f-4782-8870-2f122d0b5cc8)

Thank you for considering this suggestion, and keep up the amazing work!

Best regards!

**Comment by elchininet** [comment]
Hi @ardstuebck,

Those kinds of non-interactive elements are very different in terms of naming and DOM-location depending on the more-info dialog and they are not critical enough to dedicate an option specifically for them.

Having an option for those kinds of informative texts would open the  door for toons of options to hide whatever information certain user would like to hide. In these situations it is better to use a generic solution like `card-mod`.

Let me know if you are not able to hide it using `card-mod` and I can help you to achieve it.

Regards

**Comment by ardstuebck** [comment]
Thanks @elchininet for your quick response and the tip about card-mod. I had previously looked into card-mod and was under the impression that it couldn't be used to modify popups (more-info-dialog). That's why I asked here. Do you know of a way to achieve this? Otherwise, I could also inquire in the card-mod repository.

**Comment by elchininet** [comment]
Hi @ardstuebck,
I think that it is possible to do it with `card-nod`, I'll check it and report back.

About `browser-mod`, you can create dialogs but I don't know if you can replace the regular ones. I need to check the documentation. 

I'll update you.

**Comment by elchininet** [comment]
Hi @ardstuebck,
Here you go:

(Take into account that I have not installed Home Assistant `2025.1.1` yet and I am using the previous `card-mod` version, so I don't know if something has changed there).

Making use of [a card-mod theme](https://github.com/thomasloven/lovelace-card-mod/wiki/Card-mod-Themes), add the next code to it:

```yaml
the-name-of-your-theme:
card-mod-theme: the-name-of-your-theme
card-mod-more-info-yaml: |
  ha-more-info-info$:
    more-info-content$:
      more-info-lock$:
        ha-more-info-state-header$: |
          .last-changed {
            visibility: hidden;
          }
```
