### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by garv3** [NemesisRE/kiosk-mode#4]
I installed kiosk-mode via HACS and added this to the dashboard:
```
kiosk_mode:
  user_settings:
    - users:
        - kiosk_wz
      kiosk: true
      hide_menubutton: true
      ignore_mobile_settings: true
      ignore_entity_settings: true
```
The navigation elements are shown as before on the device for the specified user. (using Fully Kiosk Browser)

**Comment by garv3** [comment]
Maybe this is due to a compatibility issue with: https://github.com/zanna-37/hass-swipe-navigation
I am using this one as well.

**Comment by fribse** [comment]
I'm using it with my fully kiosk browser, but I've made a special panel for this. Without user settings, just 
```
kiosk_mode:
  kiosk: true
```
So 'not working at all' is a bit of a wide and unprecise description

**Comment by Lord0fBytes** [comment]
I am having the same 'issue' as above. To shed a little more light on the details:
Installed via HACS. 
Confirmed the `kiosk-mode.js` was in the `config/www/community` folder:

![Screen Shot 2022-10-03 at 11 43 20 AM](https://user-images.githubusercontent.com/7501413/193619840-29e8dc3a-6392-4d97-9ea3-2f59e4929ebb.png)

I created a nice simple Dashboard using Lovelace UI editor. Opened the raw configuration file added this to the top of the panel:
```
kiosk_mode:
  hide_header: true

views:
  - theme: Backend-selected
    title: Home 
    ... (removed the rest of the config)
```
Reloaded resources on the dashboard (no change). 
Restarted HA and still no change. I can see the sidebars and headers as if the code was not doing anything. 

I dont see anything in the logs that would indicate an issue with this integration.
