### ISSUE TITLE
hide_header no longer working on iOS app after update to 1.8.x and to HA 2023.4

### ISSUE THREAD

**Issue by gwww** [NemesisRE/kiosk-mode#52]
What happens is that `hide_header` no longer works on the iOS app. It was working before I updated - I'm guessing I was on 1.7.8 prior to the bug happening. 

What I tried and the header was never hidden:
- Closing the iOS app and restarting
- Refreshing the screen
- Turning hide on/off (see my config below)
- Tested on iOS app latest (from the last couple of days) and previous (from at least a couple months ago)

I also tried using Safari on my phone to sign into my HA instance and `hide_header` works as expected. `hide_header` also works as expected in Firefox on MacOS.

So, something new in either the latest kiosk mode or in the latest HA 2023.4 release would appear to be the problem and how one of those is interacting with the iOS app.

```
kiosk_mode:
  entity_settings:
    - entity:
        input_boolean.kiosk_mode: 'on'
      hide_header: true
    - entity:
        input_boolean.kiosk_mode: 'off'
      hide_header: false
```
