### ISSUE TITLE
Scrolling not possible with kiosk mode enabled

### ISSUE THREAD

**Issue by Protoncek** [NemesisRE/kiosk-mode#58]
As said, i can't scroll my page anymore with kiosk mode enabled. By "enabled" i mean this: i have input boolean created for this purpose, so i can turn off kiosk mode eith button card if needed. For this to work i have this code at the top of my lovelace:
```
kiosk_mode:
  admin_settings:
    kiosk: false
    ignore_entity_settings: true
  non_admin_settings:
    ignore_entity_settings: false
  entity_settings:
    - entity:
        input_boolean.kiosk_ani: 'on'
      kiosk: true
```
If i set above "input_boolean" to off, i can scroll page, but if i turn it on (so that header and side meni hides) i can't anymore.

Did i miss something in my config - has something changed or is it a bug (kiosk addon or HA...)?
