### ISSUE TITLE
kiosk_mode is an invalid option for lovelace

### ISSUE THREAD

**Issue by Marcx87** [NemesisRE/kiosk-mode#6]
After upgrading to lastest core (2022.11.5) I get the following error

`Invalid config for [lovelace]: [kiosk_mode] is an invalid option for [lovelace]. Check: lovelace->lovelace->kiosk_mode. (See /config/configuration.yaml, line 36).`

This is line 36 in configuration.yaml

`lovelace: !include plancia_custom.yaml`

and this is `plancia_custom.yaml`

```
kiosk_mode:
  user_settings:
    - users:
        - tablet
      hide_sidebar: true

mode: storage
dashboards:
  lovelace-tablet:
    mode: yaml
    title: Home
    icon: mdi:home
    show_in_sidebar: true
    filename: lovelace/lovelace-tablet.yaml
```

Any Advice?
