### ISSUE TITLE
hide options not working over Cloud access

### ISSUE THREAD

**Issue by criticallimit** [NemesisRE/kiosk-mode#68]
Have configured some of my views with following setting in lovelace view:

```
kiosk_mode:
  user_settings:
    - users:
        - Mo
      hide_sidebar: true
      hide_overflow: true
      hide_search: true
      hide_assistant: true
```

This is working good as long as "Mo" opens the view locally. But when he is connected from outside over the cloud it is no longer working. Both cases the Home Assistant App is not used, it is a browser link.

Can somebody confirm?
