### ISSUE TITLE
Lovelace config not found (during startup)

### ISSUE THREAD

**Issue by Mariusthvdb** [NemesisRE/kiosk-mode#75]
might have been there before, but only noticing now, because I had Inspector open during startup:

<img width="1145" alt="Scherm­afbeelding 2023-05-25 om 08 32 26" src="https://github.com/NemesisRE/kiosk-mode/assets/33354141/73999bfe-05f0-486a-9394-c3ab9aab3314">

Not sure if this has to do anything with my use of !includes, or yaml way of splitting the config, but it would be nice if we could prevent this from happening.

HA 2023.5.4
Kiosk Mode 1.9.0

**Comment by elchininet** [comment]
Hi @Mariusthvdb, please check manually if your config is available in that element, if not, we need to find where it went maybe due to your set up. 

Just for context, the code checks multiple times for the config and after several unsuccessful intents, it throws that warning and it continues with the default configuration.

Regards

**Comment by Mariusthvdb** [comment]
to be honest, I dont know what you are looking for...

i have a ui-lovelace.yaml in my /config root, and that has no refererence to kiosk mode.

next, my config is like this:
```
lovelace:
  mode: yaml
  resources: !include /config/dashboard/resources.yaml
  dashboards:

    ui-overzicht:
      mode: yaml
      filename: dashboard/dashboards/ui-overzicht.yaml
      title: Overzicht
      icon: mdi:home

    ui-familie:
      mode: yaml
      filename: dashboard/dashboards/ui-familie.yaml
      title: Familie
      icon: mdi:home-account

#etcetc for all other dashboards
```

and all dashboards contain a reference to kiosk-mode like this:

```

title: Ha Main #Rpi4

button_card_templates: !include_dir_merge_named ../button_card_templates
decluttering_templates: !include_dir_named ../decluttering_templates
kiosk_mode: !include ../kiosk-mode/kiosk-mode.yaml

#swipe_nav:
#  wrap: false
#  animate: swipe
#  skip_tabs: 5,6,7,8
#  prevent_default: true
#  swipe_amount: 30

views:
  - !include ui-overzicht/view_overzicht_Welkom.yaml         #0
  - !include ui-overzicht/view_overzicht_Plattegrond.yaml    #1
  # etcetc
```

anything you can spot here, or something else you need to analyze this?
